### ISSUE TITLE
Non compatible Python3.6

### ISSUE THREAD

**Issue by jltamburini** [vgalin/html2image#169]
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    from html2image import Html2Image
  File "[venv]/lib64/python3.6/site-packages/html2image/__init__.py", line 4, in <module>
    from .html2image import Html2Image
  File "[venv]/lib64/python3.6/site-packages/html2image/html2image.py", line 16, in <module>
    from html2image.browsers import chrome, chrome_cdp, edge  # , firefox, firefox_cdp
  File "<fstring>", line 1
    (r.json()=)

Python 3.6.8 (AlmaLinux Server)

**Comment by vgalin** [comment]
Hello, thanks opening an issue. Unfortunately, Python 3.6 reached end-of-life in 2021, and maintaining compatibility with unsupported versions would add unnecessary complexity to this project. Please consider upgrading to Python 3.8 or later html2image aims to supports modern Python versions.

If you absolutely need to use it with this given version, you could absolutely edit the source code at the path specified and remove the problematic imports (tied to chrome_cdp for example).

**Comment by jltamburini** [comment]
Why in home module  page you mentionned 3.6 and 3.7 ?
