### ISSUE TITLE
OSError 30

### ISSUE THREAD

**Issue by Creepy-Creeper3625** [vgalin/html2image#20]
Hello I am running the example code and got this error
```
Traceback (most recent call last):
  File "/data/user/0/ru.iiec.pydroid3/files/accomp_files/iiec_run/iiec_run.py", line 31, in <module>
    start(fakepyfile,mainpyfile)
  File "/data/user/0/ru.iiec.pydroid3/files/accomp_files/iiec_run/iiec_run.py", line 30, in start
    exec(open(mainpyfile).read(),  __main__.__dict__)
  File "<string>", line 2, in <module>
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.8/site-packages/html2image/html2image.py", line 154, in __init__
    self.temp_path = temp_path
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.8/site-packages/html2image/html2image.py", line 191, in temp_path
    os.makedirs(temp_dir, exist_ok=True)
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
OSError: [Errno 30] Read-only file system: '/tmp'

[Program finished]
```

**Comment by vgalin** [comment]
HTML2Image needs a directory where it can store html/css files so that they can then be fed to a headless browser.
The default directory on Linux based-systems is `/tmp/html2image`, but it seems from the error message that you lack the permission to do so.

To fix the issue, you can either:
- allow your user to write to `/tmp`
- or change the directory used by HTML2Image, like so:

```python
hti = Html2Image(temp_path='/my/path')
hti.screenshot(...)
```
OR
```python
hti = Html2Image()
hti.temp_path='/my/path'
hti.screenshot(...)
```

Hope this will help.

**Comment by vgalin** [comment]
I'm now closing the issue. Feel free to reopen it if the problem persists, or to open a new [discussion](https://github.com/vgalin/html2image/discussions) if you need more guidance about this.
