### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'google-chrome': 'google-chrome'

### ISSUE THREAD

**Issue by tranmanhhung** [vgalin/html2image#25]
Hi All,
I need your help.

I install google chrome on server CentOs
but my program notice error
```
Traceback (most recent call last):
  File "/home/python_crawler/backend/api-python/.venv/lib/python3.7/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/python_crawler/backend/api-python/.venv/lib/python3.7/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/home/python_crawler/backend/api-python/.venv/lib/python3.7/site-packages/flask_restful/__init__.py", line 272, in error_router
    return original_handler(e)
  File "/home/python_crawler/backend/api-python/.venv/lib/python3.7/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/python_crawler/backend/api-python/.venv/lib/python3.7/site-packages/flask/_compat.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "/home/python_crawler/backend/api-python/.venv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/python_crawler/backend/api-python/.venv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/python_crawler/backend/api-python/.venv/lib/python3.7/site-packages/flask_restful/__init__.py", line 272, in error_router
    return original_handler(e)
  File "/home/python_crawler/backend/api-python/.venv/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/python_crawler/backend/api-python/.venv/lib/python3.7/site-packages/flask/_compat.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "/home/python_crawler/backend/api-python/.venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/python_crawler/backend/api-python/.venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/python_crawler/backend/api-python/.venv/lib/python3.7/site-packages/flask_restful/__init__.py", line 468, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/python_crawler/backend/api-python/.venv/lib/python3.7/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/python_crawler/backend/api-python/.venv/lib/python3.7/site-packages/flask_restful/__init__.py", line 583, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/python_crawler/backend/api-python/api.py", line 129, in post
    hti = Html2Image()
  File "/home/python_crawler/backend/api-python/.venv/lib/python3.7/site-packages/html2image/html2image.py", line 163, in __init__
    self.chrome_path = chrome_path
  File "/home/python_crawler/backend/api-python/.venv/lib/python3.7/site-packages/html2image/html2image.py", line 176, in chrome_path
    self._chrome_path = _find_chrome(value)
  File "/home/python_crawler/backend/api-python/.venv/lib/python3.7/site-packages/html2image/html2image.py", line 60, in _find_chrome
    ["google-chrome", "-version"]
  File "/usr/local/lib/python3.7/subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "/usr/local/lib/python3.7/subprocess.py", line 472, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/local/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/local/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'google-chrome': 'google-chrome'
```

**Comment by vgalin** [comment]
Hello, please make sure that Chrome/Chromium is installed on your machine. If it's already the case, could you take a look at [this comment](https://github.com/vgalin/html2image/issues/24#issuecomment-856326802) I gave on another issue and tell me if it solves the issue? (just forget the parts about Heroku and you should be fine)

**Comment by tranmanhhung** [comment]
Hi @vgalin 

I run command line in my server 

[nginx@re ~]$ google-chrome --version
Google Chrome 91.0.4472.77 
[nginx@re ~]$ which google-chrome
/usr/bin/google-chrome

I add hti.chrome_path = '/usr/bin/google-chrome' to code but still get error

**Comment by vgalin** [comment]
I just tested it using Docker + [the latest CentOS image](https://hub.docker.com/_/centos) and couldn't reproduce the issue.

OS details:
```
[root@99a0177559ca ~]# cat /etc/*-release
CentOS Linux release 8.4.2105
NAME="CentOS Linux"
VERSION="8"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Linux 8"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"
CENTOS_MANTISBT_PROJECT="CentOS-8"
CENTOS_MANTISBT_PROJECT_VERSION="8"
CentOS Linux release 8.4.2105
CentOS Linux release 8.4.2105
```

After I installed Chrome:
```
[root@99a0177559ca ~]# google-chrome --no-sandbox --version
Google Chrome 91.0.4472.101
[root@99a0177559ca ~]# which google-chrome
/usr/bin/google-chrome
```

Taking a screenshot : 
```
Python 3.6.8 (default, Mar 19 2021, 05:13:41)
[GCC 8.4.1 20200928 (Red Hat 8.4.1-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from html2image import Html2Image
>>> hti = Html2Image()
>>> hti.custom_flags = ['--no-sandbox']
>>> hti.screenshot(url='https://www.python.org', save_as='python_org.png')
# some logs are omitted
['/root/python_org.png']
```

Then I copied the file from the container to my machine and was able to assess that the screenshot was correctly taken.

Could you try the following and share the output here ? (e.g. opening a python REPL, performing a which on google-chrome and running it with --version)

```
[root@99a0177559ca ~]# python3
Python 3.6.8 (default, Mar 19 2021, 05:13:41)
[GCC 8.4.1 20200928 (Red Hat 8.4.1-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import shutil
>>> shutil.which('google-chrome')
'/usr/bin/google-chrome'
>>> import subprocess
>>> subprocess.run(['google-chrome', '--version', '--no-sandbox'])
Google Chrome 91.0.4472.101
CompletedProcess(args=['google-chrome', '--version', '--no-sandbox'], returncode=0)
```

**Comment by tranmanhhung** [comment]
I run file on server this issue solved.
Via API Flask still error.
Thanks for your support.
