### ISSUE TITLE
Error when not using "google-chrome" under Linux : FileNotFoundError: [Errno 2] No such file or directory: 'google-chrome'

### ISSUE THREAD

**Issue by AppliNH** [vgalin/html2image#32]
Hi !

### Context

I have installed `chromium-browser` in a Ubuntu Docker container to try some things out.

### Issue

However, when I execute a python script using your package, the following stack-trace pops out : 

```
Traceback (most recent call last):
  File "/examples/load_filestr_example.py", line 19, in <module>
    hti = Html2Image()
  File "/usr/local/lib/python3.9/site-packages/html2image/html2image.py", line 84, in __init__
    self.browser = browser_class(
  File "/usr/local/lib/python3.9/site-packages/html2image/browsers/chrome.py", line 113, in __init__
    self.executable_path = executable_path
  File "/usr/local/lib/python3.9/site-packages/html2image/browsers/chrome.py", line 130, in executable_path
    self._executable_path = _find_chrome(value)
  File "/usr/local/lib/python3.9/site-packages/html2image/browsers/chrome.py", line 52, in _find_chrome
    version_result = subprocess.check_output(
  File "/usr/local/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/local/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/local/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'google-chrome'
```

### Remark

Isn't it supposed to find and use `chromium-browser` instead of `google-chrome` if this one can't be found ?

### Fix proposal

In `browsers/chrome.py`, a lot of things are happening, and some are failing.
For the Linux (Allow me to interject...) case, wouldn't it be easier to only use `which` as you've done here ?  
>

```py
which_result = shutil.which('chromium-browser')
```

Keep up the good work :)

**Comment by vgalin** [comment]
Thanks for reporting the issue, it should be resolved in the latest version (`pip install --upgrade html2image`).
Feel free to reopen it if the problem persists.
