### ISSUE TITLE
in screenshot_url     self.browser.screenshot( AttributeError: 'str' object has no attribute 'screenshot'

### ISSUE THREAD

**Issue by varnt** [vgalin/html2image#38]
**i´m trying to convert html to png files, but it always return this error:**
Traceback (most recent call last):
  File "c:\Users\...\CDCConverterWatchDog.py", line 8, in <module>
    hti.screenshot_loaded_file(file=file)
  File "C:\Users\...\Python\Python39\lib\site-packages\html2image\html2image.py", line 193, in screenshot_loaded_file
    self.browser.screenshot(
AttributeError: 'str' object has no attribute 'screenshot'
PS C:\Users\user>

code:----------------------------------------------------------------------------------
from html2image import Html2Image
hti = Html2Image()
hti.browser = 'chrome'
hti.output_path = "C:/Users/ArntV"
hti.size = (1080,1920)
file = 'C:/CDC_template.html'

hti.screenshot_loaded_file(file=file)
hti.screenshot_loaded_file(file=file,size=(1080,1920))

HTML file contents:----------------------------------------------------------------------------------
<html>
   <head>
      <style>
         .container{
         background-image: url("http://www.agcofinance.com.br/portal_dll/campanhas/Comunicados/Imagens_RD_Station/CDC Template/Background_AGCO.png");
         background-repeat: no-repeat;
         background-size: 100% 100%; /* width height */
         width:1080px;
         height:1920px;
         margin:0px;
         }
      </style>
      <meta content="telephone=no" name="format-detection">
      <meta content="text/html; charset=utf-8" http-equiv="Content-Type">
      <meta content="width=device-width" name="viewport">
      <link href="../css/app.css" rel="stylesheet" type="text/css">
      <title>teste</title>
   </head>
   <body style="background-color:#9a151c;width:1080px;height:1920px; marign:0px;">
      <div class="container">
         <div style="padding-left: 10%;padding-right: 10%;padding-top: 2% ;width:80%;height:10%; marign:0px;">
            <p ><b><span lang="PT-BR" style="font-size:50.0pt;font-family:&quot;Franklin Gothic Book&quot;,sans-serif;color:#ffffff;mso-ansi-language:PT-BR">
               Confira as nossas condições de *|MES|* de *|ANO|*
               </span></b>
            </p>
         </div>
         <div style="display: flex;padding-left: 10%;padding-right: 10%;width:80%;height:15%; marign:0px;">
            <div style="width:40%;height:100%; marign:0px;">
               <img style="width: 100%;height: 100%;object-fit:scale-down;" src="http://www.agcofinance.com.br/portal_dll/campanhas/Comunicados/Imagens_RD_Station/CDC Template/100financiado_AGCO.png">
            </div>
            <div style="width:60%;height:100%; marign:0px;">
               <img style="width: 100%;height: 100%;object-fit:scale-down;" src="http://www.agcofinance.com.br/portal_dll/campanhas/Comunicados/Imagens_RD_Station/CDC Template/AGROMAIS_logo.png">
            </div>
         </div>
         <div style="padding-left: 10%;padding-right: 10%;width:80%;height:50%; marign:0px;">
            <table style="width:100%;height:75%; marign:0px;">
               <tbody>
                  <tr style="background-color:#9a151c;">
                     <td style="text-align: center;">
                        <p style="text-align: center;" ><b><span lang="PT-BR" style="font-size:25.0pt;font-family:&quot;Franklin Gothic Book&quot;,sans-serif;color:#ffffff;mso-ansi-language:PT-BR">
                           PRAZO (MESES)
                           </span></b>
                        </p>
                     </td>
                     <td style="text-align: center;">
                        <p style="text-align: center;" ><b><span lang="PT-BR" style="font-size:25.0pt;font-family:&quot;Franklin Gothic Book&quot;,sans-serif;color:#ffffff;mso-ansi-language:PT-BR">
                           TAXA%
                           </span></b>
                        </p>
                        <p style="text-align: center;" ><b><span lang="PT-BR" style="font-size:15.0pt;font-family:&quot;Franklin Gothic Book&quot;,sans-serif;color:#ffffff;mso-ansi-language:PT-BR">
                           (periocidade mensal)
                           </span></b>
                        </p>
                     </td>
                     <td style="text-align: center;">
                        <p style="text-align: center;" ><b><span lang="PT-BR" style="font-size:25.0pt;font-family:&quot;Franklin Gothic Book&quot;,sans-serif;color:#ffffff;mso-ansi-language:PT-BR">
                           TAXA%
                           </span></b>
                        </p>
                        <p style="text-align: center;" ><b><span lang="PT-BR" style="font-size:15.0pt;font-family:&quot;Franklin Gothic Book&quot;,sans-serif;color:#ffffff;mso-ansi-language:PT-BR">
                           (periocidade anual)
                           </span></b>
                        </p>
                     </td>
                  </tr>
                  <tr style="background-color:#AC1936;">
                     <td style="text-align: center;">
                        <p style="text-align: center;" ><b><span lang="PT-BR" style="font-size:25.0pt;font-family:&quot;Franklin Gothic Book&quot;,sans-serif;color:#ffffff;mso-ansi-language:PT-BR">
                           12
                           </span></b>
                        </p>
                     </td>
                     <td style="text-align: center;">
                        <p style="text-align: center;" ><b><span lang="PT-BR" style="font-size:25.0pt;font-family:&quot;Franklin Gothic Book&quot;,sans-serif;color:#ffffff;mso-ansi-language:PT-BR">
                           *|TAXAM12|*
                           </span></b>
                        </p>
                     </td>
                     <td style="text-align: center;">
                        <p style="text-align: center;" ><b><span lang="PT-BR" style="font-size:25.0pt;font-family:&quot;Franklin Gothic Book&quot;,sans-serif;color:#ffffff;mso-ansi-language:PT-BR">
                           *|TAXAA12|*
                           </span></b>
                        </p>
                     </td>
                  </tr>
                  <tr style="background-color:#9a151c;">
                     <td style="text-align: center;">
                        <p style="text-align: center;" ><b><span lang="PT-BR" style="font-size:25.0pt;font-family:&quot;Franklin Gothic Book&quot;,sans-serif;color:#ffffff;mso-ansi-language:PT-BR">
                           24
                           </span></b>
                        </p>
                     </td>
                     <td style="text-align: center;">
                        <p style="text-align: center;" ><b><span lang="PT-BR" style="font-size:25.0pt;font-family:&quot;Franklin Gothic Book&quot;,sans-serif;color:#ffffff;mso-ansi-language:PT-BR">
                           *|TAXAM24|*
                           </span></b>
                        </p>
                     </td>
                     <td style="text-align: center;">
                        <p style="text-align: center;" ><b><span lang="PT-BR" style="font-size:25.0pt;font-family:&quot;Franklin Gothic Book&quot;,sans-serif;color:#ffffff;mso-ansi-language:PT-BR">
                           *|TAXAA24|*
                           </span></b>
                        </p>
                     </td>
                  </tr>
                  <tr style="background-color:#AC1936;">
                     <td style="text-align: center;">
                        <p style="text-align: center;" ><b><span lang="PT-BR" style="font-size:25.0pt;font-family:&quot;Franklin Gothic Book&quot;,sans-serif;color:#ffffff;mso-ansi-language:PT-BR">
                           36
                           </span></b>
                        </p>
                     </td>
                     <td style="text-align: center;">
                        <p style="text-align: center;" ><b><span lang="PT-BR" style="font-size:25.0pt;font-family:&quot;Franklin Gothic Book&quot;,sans-serif;color:#ffffff;mso-ansi-language:PT-BR">
                           *|TAXAM36|*
                           </span></b>
                        </p>
                     </td>
                     <td style="text-align: center;">
                        <p style="text-align: center;" ><b><span lang="PT-BR" style="font-size:25.0pt;font-family:&quot;Franklin Gothic Book&quot;,sans-serif;color:#ffffff;mso-ansi-language:PT-BR">
                           *|TAXAA36|*
                           </span></b>
                        </p>
                     </td>
                  </tr>
                  <tr style="background-color:#9a151c;">
                     <td style="text-align: center;">
                        <p style="text-align: center;" ><b><span lang="PT-BR" style="font-size:25.0pt;font-family:&quot;Franklin Gothic Book&quot;,sans-serif;color:#ffffff;mso-ansi-language:PT-BR">
                           48
                           </span></b>
                        </p>
                     </td>
                     <td style="text-align: center;">
                        <p style="text-align: center;" ><b><span lang="PT-BR" style="font-size:25.0pt;font-family:&quot;Franklin Gothic Book&quot;,sans-serif;color:#ffffff;mso-ansi-language:PT-BR">
                           *|TAXAM48|*
                           </span></b>
                        </p>
                     </td>
                     <td style="text-align: center;">
                        <p style="text-align: center;" ><b><span lang="PT-BR" style="font-size:25.0pt;font-family:&quot;Franklin Gothic Book&quot;,sans-serif;color:#ffffff;mso-ansi-language:PT-BR">
                           *|TAXAA48|*
                           </span></b>
                        </p>
                     </td>
                  </tr>
                  <tr style="background-color:#AC1936;">
                     <td style="text-align: center;">
                        <p style="text-align: center;" ><b><span lang="PT-BR" style="font-size:25.0pt;font-family:&quot;Franklin Gothic Book&quot;,sans-serif;color:#ffffff;mso-ansi-language:PT-BR">
                           60
                           </span></b>
                        </p>
                     </td>
                     <td style="text-align: center;">
                        <p style="text-align: center;" ><b><span lang="PT-BR" style="font-size:25.0pt;font-family:&quot;Franklin Gothic Book&quot;,sans-serif;color:#ffffff;mso-ansi-language:PT-BR">
                           *|TAXAM60|*
                           </span></b>
                        </p>
                     </td>
                     <td style="text-align: center;">
                        <p style="text-align: center;" ><b><span lang="PT-BR" style="font-size:25.0pt;font-family:&quot;Franklin Gothic Book&quot;,sans-serif;color:#ffffff;mso-ansi-language:PT-BR">
                           *|TAXAA60|*
                           </span></b>
                        </p>
                     </td>
                  </tr>
               </tbody>
            </table>
            <div style="height:5%;marign:0px;">
               <p style="text-align: center;" ><b><span lang="PT-BR" style="font-size:25.0pt;font-family:&quot;Franklin Gothic Book&quot;,sans-serif;color:#ffffff;mso-ansi-language:PT-BR">
                  Vigência: até *|VIGENCIA|*
                  </span></b>
               </p>
            </div>
            <hr style="border: 1px solid #ffffff;" />
            <div style="height:5%;marign:0px;">
               <p style="text-align: center;" ><span lang="PT-BR" style="font-size:25.0pt;font-family:&quot;Franklin Gothic Book&quot;,sans-serif;color:#ffffff;mso-ansi-language:PT-BR">
                  <b>Carência:</b>
                  até 18 meses, de acordo com a safra do cliente
                  </span>
               </p>
            </div>
            <hr style="border: 1px solid #ffffff;" />
            <div style="height:5%;marign:0px;">
               <p style="text-align: center;" ><span lang="PT-BR" style="font-size:25.0pt;font-family:&quot;Franklin Gothic Book&quot;,sans-serif;color:#ffffff;mso-ansi-language:PT-BR">
                  <b>Forma de pagamento:</b>
                  mensal, bimestral, trimestral, quadrimestral, semestral ou anual
                  </span>
               </p>
            </div>

         </div>
         <div style="display: flex;padding-left: 10%;padding-top: 2%;padding-right: 10%;width:80%;height:20%; marign:0px;">
            <div style="padding-left: 5%;padding-right: 5%;width:70%;height:100%; marign:0px;">
               <p style="text-align: left;" ><span lang="PT-BR" style="font-size:18.0pt;font-family:&quot;Franklin Gothic Book&quot;,sans-serif;color:#ffffff;mso-ansi-language:PT-BR">
                  Condições válidas para financiamentos através da linha CDC – Crédito Direto ao Consumidor. Condições válidas apenas para financiamentos com prazo de citados na tabela acima. Condições comerciais para Pessoas Físicas e Pessoas Jurídicas. Os vencimentos das parcelas serão ajustados em função dos finais de semana e/ou feriados; Para condições comerciais diferenciadas, consulte um representante comercial. Condições sujeitas a alterações em caso de flutuações de mercado e sem aviso prévio. Condições de CDC praticadas pelo Banco de Lage Landen Brasil S.A.. Condições sujeitas a aprovação de crédito pelo Banco De Lage Landen S.A.
                  </span>
               </p>
            </div>
            <div style="width:20%;height:100%; marign:0px;">
              <img style="width: 100%;height: 100%;object-fit:scale-down;" src="http://www.agcofinance.com.br/portal_dll/campanhas/Comunicados/Imagens_RD_Station/CDC Template/AGCO_Finance_logo.png">
            </div>
         </div>
         <div style="display: flex;padding-left: 10%;padding-right: 10%;width:80%;height:1%; marign:0px;">
               <p style="text-align: center;" ><span lang="PT-BR" style="font-size:15.0pt;font-family:&quot;Franklin Gothic Book&quot;,sans-serif;color:#ffffff;mso-ansi-language:PT-BR">
                 AGCO FINANCE é uma marca registrada e unidade de negócios do Banco De Lage Landen Brasil S.A.
                  </span>
               </p>

         </div>
      </div>
   </body>
</html>

**Comment by vgalin** [comment]
Hello, thanks for reporting this issue. There is indeed a problem when a browser is set after instanciating an Html2Image object.
It will be fixed in a later release of the package.

For the moment, as chrome is the only browser available and is used by default, you can use the following code:
```python
from html2image import Html2Image

hti = Html2Image()
# no need to set 'chrome' as the browser because it is the default option
hti.output_path = "C:/Users/ArntV"
hti.size = (1080,1920)
file = 'C:/CDC_template.html'

# use screenshote instead of screenshot_loaded_file
hti.screenshot(html_file=file)
```

Tell me if you still have any problem. Also please do not close the issue for the moment.
