### ISSUE TITLE
Image is not loading

### ISSUE THREAD

**Issue by RobertSchueler** [vgalin/html2image#47]
I have a very small project on a Windows 10 machine with the following image in the file example.png:

![image](https://user-images.githubusercontent.com/70914876/136830798-ae0983a8-07fe-404f-a585-dbcd467602be.png)

I try to make a screenshot of a simple html project using the following code:

```
from html2image import Html2Image

hti = Html2Image()

html_str ="""
<!DOCTYPE html>
<html>
    <body>
        <img src="example.jpg">
    </body>
</html>
"""

css_str = """
body {
  margin: 0;
  background: black;
}
"""

hti.screenshot(html_str=html_str, css_str=css_str, save_as="test.png")
```

I would expect to see the image in the result. But it only results in the following:

![test](https://user-images.githubusercontent.com/70914876/136830998-7e4c99d7-d05a-4316-b870-18ed4ba241e5.png)

If I copy the html and css strings to a file (and link them) I can see the expected result with my browser. So I guess it has nothing to do with reading access or so.

![image](https://user-images.githubusercontent.com/70914876/136831293-f7ac2ce8-3fd7-4447-b966-3e1db6d29480.png)

**Comment by RobertSchueler** [comment]
Thanks a lot, worked like a charm.

**Comment by MartinPicc** [comment]
As an alternative, you can also load png as base64 string into the HTML itself.

Example:
```
# replace src path with base64 encoded string
png_paths = re.findall('src="(\S+?.png)"', html)
for png_path in png_paths:
    with open(png_path, 'rb') as f:
        base64_png = 'data:image/png;base64, ' + base64.b64encode(f.read()).decode('ascii')
    html = html.replace(png_path, base64_png)
```
It uses a regex expression to detect `src` tags ending with `.png` (and defined with double quotes) in the HTML. Then it opens each image, converts them to base64 string, and injects them back into the HTML

**Comment by GAumala** [comment]
Changing `temp_path` to the working directory is not a good workaround. If you pass `html_file` inside the current working directory it will try to copy it and throw `SameFileError`

```
Traceback (most recent call last):
  File "/Users/gabriel/playground/html2png.py", line 100, in <module>
    main()
    ~~~~^^
  File "/Users/gabriel/playground/html2png.py", line 91, in main
    hti.screenshot(
    ~~~~~~~~~~~~~~^
        html_file=str(html_path),
        ^^^^^^^^^^^^^^^^^^^^^^^^^
        save_as=str(output_path),
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/gabriel/.cache/uv/environments-v2/html2png-348e33b47c3b637c/lib/python3.14/site-packages/htm
l2image/html2image.py", line 566, in screenshot
    self.load_file(src=screenshot_target)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gabriel/.cache/uv/environments-v2/html2png-348e33b47c3b637c/lib/python3.14/site-packages/htm
l2image/html2image.py", line 186, in load_file
    shutil.copyfile(src, dest)
    ~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.14/3.14.3_1/Frameworks/Python.framework/Versions/3.14/lib/python3.14/
shutil.py", line 293, in copyfile
    raise SameFileError("{!r} and {!r} are the same file".format(src, dst))
shutil.SameFileError: '/Users/gabriel/playground/post1.html' and '/Users/gab
riel/playground/post1.html' are the same file
```
